# Generated by Django 3.1.13 on 2022-03-16 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id Клиента')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^(7+([0-9]){10})$')], verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=3, verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(max_length=100, verbose_name='Тэг (произвольная метка)')),
                ('UTC', models.FloatField(verbose_name='часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id Рассылки')),
                ('content', models.TextField(verbose_name='Текст сообщения отправки')),
                ('filter', models.TextField(verbose_name='Фильтр свойств клиентов (код оператора, тэг)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время запуска рассылки')),
                ('ended_at', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id Сообщения')),
                ('status', models.CharField(max_length=20, verbose_name='Статус отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания сообщения')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spam.client')),
                ('spam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spam.spam')),
            ],
        ),
    ]
