# Generated by Django 3.1.13 on 2022-03-16 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='spam',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылка'},
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Набран неверный формат номера телефона, введите в формате: 7XXXXXXXXXX (X - цифра от 0 до 9)', regex='^(7+([0-9]){10})$')], verbose_name='Номер телефона'),
        ),
    ]
