# Generated by Django 3.1.13 on 2022-03-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0003_auto_20220316_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='UTC',
            field=models.CharField(max_length=10, verbose_name='Часовой пояс'),
        ),
    ]
