# Generated by Django 3.1.13 on 2022-03-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0004_auto_20220316_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='started_at',
            field=models.DateTimeField(verbose_name='Дата и время запуска рассылки'),
        ),
    ]
