# Generated by Django 3.1.13 on 2022-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0005_auto_20220316_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='client_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='spam_id',
            field=models.IntegerField(),
        ),
    ]
